/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dev.androidbroadcast.framesdk.models.AdminOnlyAction

class AdminOnlyActionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AdminOnlyAction
        //val modelInstance = AdminOnlyAction()

        // to test the property `lifecycle`
        should("test lifecycle") {
            // uncomment below to test the property
            //modelInstance.lifecycle shouldBe ("TODO")
        }

    }
}
