/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dev.androidbroadcast.framesdk.models.AssetSubtitle

class AssetSubtitleTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AssetSubtitle
        //val modelInstance = AssetSubtitle()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `subtitleTracks`
        should("test subtitleTracks") {
            // uncomment below to test the property
            //modelInstance.subtitleTracks shouldBe ("TODO")
        }

    }
}
