/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dev.androidbroadcast.framesdk.models.AssetSearch
import dev.androidbroadcast.framesdk.models.AssetSearchGetTeamIdParameter

class AssetSearchTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AssetSearch
        //val modelInstance = AssetSearch()

        // to test the property `accountId`
        should("test accountId") {
            // uncomment below to test the property
            //modelInstance.accountId shouldBe ("TODO")
        }

        // to test the property `filter` - Custom ES filters to apply to your query
        should("test filter") {
            // uncomment below to test the property
            //modelInstance.filter shouldBe ("TODO")
        }

        // to test the property `include`
        should("test include") {
            // uncomment below to test the property
            //modelInstance.include shouldBe ("TODO")
        }

        // to test the property `includeDeleted` - Flag to include soft-deleted records in results
        should("test includeDeleted") {
            // uncomment below to test the property
            //modelInstance.includeDeleted shouldBe ("TODO")
        }

        // to test the property `opts` - Additional request options
        should("test opts") {
            // uncomment below to test the property
            //modelInstance.opts shouldBe ("TODO")
        }

        // to test the property `page` - The page to retrieve
        should("test page") {
            // uncomment below to test the property
            //modelInstance.page shouldBe ("TODO")
        }

        // to test the property `pageSize` - The number of results to include in the page
        should("test pageSize") {
            // uncomment below to test the property
            //modelInstance.pageSize shouldBe ("TODO")
        }

        // to test the property `projectId`
        should("test projectId") {
            // uncomment below to test the property
            //modelInstance.projectId shouldBe ("TODO")
        }

        // to test the property `properties`
        should("test properties") {
            // uncomment below to test the property
            //modelInstance.properties shouldBe ("TODO")
        }

        // to test the property `q` - Search text
        should("test q") {
            // uncomment below to test the property
            //modelInstance.q shouldBe ("TODO")
        }

        // to test the property `query` - Search text
        should("test query") {
            // uncomment below to test the property
            //modelInstance.query shouldBe ("TODO")
        }

        // to test the property `sharedProjects`
        should("test sharedProjects") {
            // uncomment below to test the property
            //modelInstance.sharedProjects shouldBe ("TODO")
        }

        // to test the property `sort` - Sorting parameters
        should("test sort") {
            // uncomment below to test the property
            //modelInstance.sort shouldBe ("TODO")
        }

        // to test the property `teamId`
        should("test teamId") {
            // uncomment below to test the property
            //modelInstance.teamId shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

    }
}
