/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dev.androidbroadcast.framesdk.models.Audit
import dev.androidbroadcast.framesdk.models.AuditActor

class AuditTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Audit
        //val modelInstance = Audit()

        // to test the property `accountId`
        should("test accountId") {
            // uncomment below to test the property
            //modelInstance.accountId shouldBe ("TODO")
        }

        // to test the property `action`
        should("test action") {
            // uncomment below to test the property
            //modelInstance.action shouldBe ("TODO")
        }

        // to test the property `actor`
        should("test actor") {
            // uncomment below to test the property
            //modelInstance.actor shouldBe ("TODO")
        }

        // to test the property `actorId`
        should("test actorId") {
            // uncomment below to test the property
            //modelInstance.actorId shouldBe ("TODO")
        }

        // to test the property `applicationId`
        should("test applicationId") {
            // uncomment below to test the property
            //modelInstance.applicationId shouldBe ("TODO")
        }

        // to test the property `insertedAt`
        should("test insertedAt") {
            // uncomment below to test the property
            //modelInstance.insertedAt shouldBe ("TODO")
        }

        // to test the property `ipAddress`
        should("test ipAddress") {
            // uncomment below to test the property
            //modelInstance.ipAddress shouldBe ("TODO")
        }

        // to test the property `itemId`
        should("test itemId") {
            // uncomment below to test the property
            //modelInstance.itemId shouldBe ("TODO")
        }

        // to test the property `itemType`
        should("test itemType") {
            // uncomment below to test the property
            //modelInstance.itemType shouldBe ("TODO")
        }

        // to test the property `requestId`
        should("test requestId") {
            // uncomment below to test the property
            //modelInstance.requestId shouldBe ("TODO")
        }

        // to test the property `resource`
        should("test resource") {
            // uncomment below to test the property
            //modelInstance.resource shouldBe ("TODO")
        }

        // to test the property `teamId`
        should("test teamId") {
            // uncomment below to test the property
            //modelInstance.teamId shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

    }
}
