/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dev.androidbroadcast.framesdk.models.BatchCopyAsset200ResponseSuccesTest

class BatchCopyAsset200ResponseSuccesTestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BatchCopyAsset200ResponseSuccesTest
        //val modelInstance = BatchCopyAsset200ResponseSuccesTest()

        // to test the property ``
        should("test ") {
            // uncomment below to test the property
            //modelInstance. shouldBe ("TODO")
        }

    }
}
