/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dev.androidbroadcast.framesdk.models.BatchCopyAssetRequest
import dev.androidbroadcast.framesdk.models.BatchCopyAssetRequestBatchInner

class BatchCopyAssetRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BatchCopyAssetRequest
        //val modelInstance = BatchCopyAssetRequest()

        // to test the property `batch`
        should("test batch") {
            // uncomment below to test the property
            //modelInstance.batch shouldBe ("TODO")
        }

        // to test the property `copyComments`
        should("test copyComments") {
            // uncomment below to test the property
            //modelInstance.copyComments shouldBe ("TODO")
        }

    }
}
