/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dev.androidbroadcast.framesdk.models.BatchInviteParams
import dev.androidbroadcast.framesdk.models.BatchInviteParamsBatchInner

class BatchInviteParamsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BatchInviteParams
        //val modelInstance = BatchInviteParams()

        // to test the property `batch`
        should("test batch") {
            // uncomment below to test the property
            //modelInstance.batch shouldBe ("TODO")
        }

        // to test the property `defaultMessage` - Default invite message to be applied to all invites created
        should("test defaultMessage") {
            // uncomment below to test the property
            //modelInstance.defaultMessage shouldBe ("TODO")
        }

        // to test the property `sendEmail` - When false no emails will be sent to the new Reviewers and Pending Reviewers
        should("test sendEmail") {
            // uncomment below to test the property
            //modelInstance.sendEmail shouldBe ("TODO")
        }

    }
}
