/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dev.androidbroadcast.framesdk.models.BatchDeleteCollaboratorsRequest
import dev.androidbroadcast.framesdk.models.BatchDeleteCollaboratorsRequestBatchInner

class BatchDeleteCollaboratorsRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BatchDeleteCollaboratorsRequest
        //val modelInstance = BatchDeleteCollaboratorsRequest()

        // to test the property `batch`
        should("test batch") {
            // uncomment below to test the property
            //modelInstance.batch shouldBe ("TODO")
        }

    }
}
