/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dev.androidbroadcast.framesdk.models.CreateActionForTeamRequest

class CreateActionForTeamRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateActionForTeamRequest
        //val modelInstance = CreateActionForTeamRequest()

        // to test the property `description` - Description of the custom Action
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `event` - Arbitrary event name to include in custom Action webhook payloads
        should("test event") {
            // uncomment below to test the property
            //modelInstance.event shouldBe ("TODO")
        }

        // to test the property `name` - Name of the custom Action
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `url` - HTTPS endpoint to deliver Action events to
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `allowCollaborators`
        should("test allowCollaborators") {
            // uncomment below to test the property
            //modelInstance.allowCollaborators shouldBe ("TODO")
        }

        // to test the property `include` - Any associations to include in the response
        should("test include") {
            // uncomment below to test the property
            //modelInstance.include shouldBe ("TODO")
        }

    }
}
