/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dev.androidbroadcast.framesdk.models.CreateWebhookForTeamRequest

class CreateWebhookForTeamRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateWebhookForTeamRequest
        //val modelInstance = CreateWebhookForTeamRequest()

        // to test the property `name` - Name of the Webhook
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `url` - HTTPS endpoint to delivery events to
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `events`
        should("test events") {
            // uncomment below to test the property
            //modelInstance.events shouldBe ("TODO")
        }

    }
}
