/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dev.androidbroadcast.framesdk.models.CreateRealtimeUploadParts200Response

class CreateRealtimeUploadParts200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateRealtimeUploadParts200Response
        //val modelInstance = CreateRealtimeUploadParts200Response()

        // to test the property `uploadUrls` - Array of AWS S3 presigned upload PUT URLs.  Returned in the same order as the `parts` field of the request.
        should("test uploadUrls") {
            // uncomment below to test the property
            //modelInstance.uploadUrls shouldBe ("TODO")
        }

    }
}
