/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dev.androidbroadcast.framesdk.models.DeviceListAccounts200ResponseInner

class DeviceListAccounts200ResponseInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DeviceListAccounts200ResponseInner
        //val modelInstance = DeviceListAccounts200ResponseInner()

        // to test the property `type` - The resource type, will always be `account`.
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `displayName` - The account's display name
        should("test displayName") {
            // uncomment below to test the property
            //modelInstance.displayName shouldBe ("TODO")
        }

        // to test the property `id` - The unique identifier for this account
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

    }
}
