/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dev.androidbroadcast.framesdk.models.DeviceRequestCode200Response

class DeviceRequestCode200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DeviceRequestCode200Response
        //val modelInstance = DeviceRequestCode200Response()

        // to test the property `deviceCode` - The device code should be hidden from the user, and is used to identify this authorization request when polling to see if the user has entered their code successfully.
        should("test deviceCode") {
            // uncomment below to test the property
            //modelInstance.deviceCode shouldBe ("TODO")
        }

        // to test the property `expiresIn` - The number of seconds until this code expires.
        should("test expiresIn") {
            // uncomment below to test the property
            //modelInstance.expiresIn shouldBe ("TODO")
        }

        // to test the property `interval` - How long the we should wait between polling requests to see if the user has entered the code.
        should("test interval") {
            // uncomment below to test the property
            //modelInstance.interval shouldBe ("TODO")
        }

        // to test the property `name` - The name of the device we are trying to connect.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `userCode` - The six-digit code the user will enter into Frame.io to pair the device to a project.
        should("test userCode") {
            // uncomment below to test the property
            //modelInstance.userCode shouldBe ("TODO")
        }

    }
}
