/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dev.androidbroadcast.framesdk.models.GetGroupedNotifications200ResponseTextElementsBodyInner

class GetGroupedNotifications200ResponseTextElementsBodyInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetGroupedNotifications200ResponseTextElementsBodyInner
        //val modelInstance = GetGroupedNotifications200ResponseTextElementsBodyInner()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `format`
        should("test format") {
            // uncomment below to test the property
            //modelInstance.format shouldBe ("TODO")
        }

        // to test the property ``value``
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

    }
}
