/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dev.androidbroadcast.framesdk.models.GetGroupedNotifications200ResponseTextElements
import dev.androidbroadcast.framesdk.models.GetGroupedNotifications200ResponseTextElementsBodyInner
import dev.androidbroadcast.framesdk.models.GetGroupedNotifications200ResponseTextElementsHeaderInner

class GetGroupedNotifications200ResponseTextElementsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetGroupedNotifications200ResponseTextElements
        //val modelInstance = GetGroupedNotifications200ResponseTextElements()

        // to test the property `header`
        should("test header") {
            // uncomment below to test the property
            //modelInstance.header shouldBe ("TODO")
        }

        // to test the property `body`
        should("test body") {
            // uncomment below to test the property
            //modelInstance.body shouldBe ("TODO")
        }

        // to test the property `footer`
        should("test footer") {
            // uncomment below to test the property
            //modelInstance.footer shouldBe ("TODO")
        }

    }
}
