/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dev.androidbroadcast.framesdk.models.GetProjectCollaborators201ResponseInnerUserRoles

class GetProjectCollaborators201ResponseInnerUserRolesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetProjectCollaborators201ResponseInnerUserRoles
        //val modelInstance = GetProjectCollaborators201ResponseInnerUserRoles()

        // to test the property `admin`
        should("test admin") {
            // uncomment below to test the property
            //modelInstance.admin shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `sales`
        should("test sales") {
            // uncomment below to test the property
            //modelInstance.sales shouldBe ("TODO")
        }

        // to test the property `support`
        should("test support") {
            // uncomment below to test the property
            //modelInstance.support shouldBe ("TODO")
        }

    }
}
