/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dev.androidbroadcast.framesdk.models.GetProjectCollaborators201ResponseInnerUserProjectRole

class GetProjectCollaborators201ResponseInnerUserProjectRoleTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetProjectCollaborators201ResponseInnerUserProjectRole
        //val modelInstance = GetProjectCollaborators201ResponseInnerUserProjectRole()

        // to test the property `collaborator`
        should("test collaborator") {
            // uncomment below to test the property
            //modelInstance.collaborator shouldBe ("TODO")
        }

        // to test the property `owner`
        should("test owner") {
            // uncomment below to test the property
            //modelInstance.owner shouldBe ("TODO")
        }

        // to test the property `teamMember`
        should("test teamMember") {
            // uncomment below to test the property
            //modelInstance.teamMember shouldBe ("TODO")
        }

        // to test the property `teamRole`
        should("test teamRole") {
            // uncomment below to test the property
            //modelInstance.teamRole shouldBe ("TODO")
        }

    }
}
