/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dev.androidbroadcast.framesdk.models.MetadataFlags

class MetadataFlagsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MetadataFlags
        //val modelInstance = MetadataFlags()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `is360`
        should("test is360") {
            // uncomment below to test the property
            //modelInstance.is360 shouldBe ("TODO")
        }

        // to test the property `isHdr`
        should("test isHdr") {
            // uncomment below to test the property
            //modelInstance.isHdr shouldBe ("TODO")
        }

        // to test the property `isOriginalPlayerCompatible`
        should("test isOriginalPlayerCompatible") {
            // uncomment below to test the property
            //modelInstance.isOriginalPlayerCompatible shouldBe ("TODO")
        }

    }
}
