/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dev.androidbroadcast.framesdk.models.ProjectDeviceAuthorizationAuthorization
import dev.androidbroadcast.framesdk.models.ProjectDeviceAuthorizationAuthorizationCreator
import dev.androidbroadcast.framesdk.models.ProjectDeviceAuthorizationAuthorizationScopes

class ProjectDeviceAuthorizationAuthorizationTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProjectDeviceAuthorizationAuthorization
        //val modelInstance = ProjectDeviceAuthorizationAuthorization()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `creator`
        should("test creator") {
            // uncomment below to test the property
            //modelInstance.creator shouldBe ("TODO")
        }

        // to test the property `creatorId`
        should("test creatorId") {
            // uncomment below to test the property
            //modelInstance.creatorId shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `insertedAt`
        should("test insertedAt") {
            // uncomment below to test the property
            //modelInstance.insertedAt shouldBe ("TODO")
        }

        // to test the property `projectDeviceId`
        should("test projectDeviceId") {
            // uncomment below to test the property
            //modelInstance.projectDeviceId shouldBe ("TODO")
        }

        // to test the property `scopes`
        should("test scopes") {
            // uncomment below to test the property
            //modelInstance.scopes shouldBe ("TODO")
        }

        // to test the property `expiresAt`
        should("test expiresAt") {
            // uncomment below to test the property
            //modelInstance.expiresAt shouldBe ("TODO")
        }

    }
}
