/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dev.androidbroadcast.framesdk.models.ProjectDeviceChannel

class ProjectDeviceChannelTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProjectDeviceChannel
        //val modelInstance = ProjectDeviceChannel()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `actorId`
        should("test actorId") {
            // uncomment below to test the property
            //modelInstance.actorId shouldBe ("TODO")
        }

        // to test the property `assetType`
        should("test assetType") {
            // uncomment below to test the property
            //modelInstance.assetType shouldBe ("TODO")
        }

        // to test the property `deviceId`
        should("test deviceId") {
            // uncomment below to test the property
            //modelInstance.deviceId shouldBe ("TODO")
        }

        // to test the property `externalIndex`
        should("test externalIndex") {
            // uncomment below to test the property
            //modelInstance.externalIndex shouldBe ("TODO")
        }

        // to test the property `insertedAt`
        should("test insertedAt") {
            // uncomment below to test the property
            //modelInstance.insertedAt shouldBe ("TODO")
        }

        // to test the property `name` - Auto-generated name, based on the device model
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `projectId` - The Project ID that this device is linked to
        should("test projectId") {
            // uncomment below to test the property
            //modelInstance.projectId shouldBe ("TODO")
        }

        // to test the property `projectDeviceId`
        should("test projectDeviceId") {
            // uncomment below to test the property
            //modelInstance.projectDeviceId shouldBe ("TODO")
        }

        // to test the property `realTimeLoggingCapable`
        should("test realTimeLoggingCapable") {
            // uncomment below to test the property
            //modelInstance.realTimeLoggingCapable shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

    }
}
