/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dev.androidbroadcast.framesdk.models.ProjectDeviceAuthorization
import dev.androidbroadcast.framesdk.models.ProjectDeviceAuthorizationAuthorization
import dev.androidbroadcast.framesdk.models.ProjectDeviceAuthorizationProject
import dev.androidbroadcast.framesdk.models.ProjectDeviceChannel

class ProjectDeviceAuthorizationTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProjectDeviceAuthorization
        //val modelInstance = ProjectDeviceAuthorization()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `assetType`
        should("test assetType") {
            // uncomment below to test the property
            //modelInstance.assetType shouldBe ("TODO")
        }

        // to test the property `authorization`
        should("test authorization") {
            // uncomment below to test the property
            //modelInstance.authorization shouldBe ("TODO")
        }

        // to test the property `channels`
        should("test channels") {
            // uncomment below to test the property
            //modelInstance.channels shouldBe ("TODO")
        }

        // to test the property `creatorId`
        should("test creatorId") {
            // uncomment below to test the property
            //modelInstance.creatorId shouldBe ("TODO")
        }

        // to test the property `deviceId`
        should("test deviceId") {
            // uncomment below to test the property
            //modelInstance.deviceId shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `insertedAt`
        should("test insertedAt") {
            // uncomment below to test the property
            //modelInstance.insertedAt shouldBe ("TODO")
        }

        // to test the property `lastSeenAt`
        should("test lastSeenAt") {
            // uncomment below to test the property
            //modelInstance.lastSeenAt shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `project`
        should("test project") {
            // uncomment below to test the property
            //modelInstance.project shouldBe ("TODO")
        }

        // to test the property `projectId`
        should("test projectId") {
            // uncomment below to test the property
            //modelInstance.projectId shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `timezone`
        should("test timezone") {
            // uncomment below to test the property
            //modelInstance.timezone shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `deletedAt`
        should("test deletedAt") {
            // uncomment below to test the property
            //modelInstance.deletedAt shouldBe ("TODO")
        }

    }
}
