/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dev.androidbroadcast.framesdk.models.ProjectPreferences

class ProjectPreferencesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProjectPreferences
        //val modelInstance = ProjectPreferences()

        // to test the property `collaboratorCanDownload`
        should("test collaboratorCanDownload") {
            // uncomment below to test the property
            //modelInstance.collaboratorCanDownload shouldBe ("TODO")
        }

        // to test the property `collaboratorCanInvite`
        should("test collaboratorCanInvite") {
            // uncomment below to test the property
            //modelInstance.collaboratorCanInvite shouldBe ("TODO")
        }

        // to test the property `collaboratorCanShare`
        should("test collaboratorCanShare") {
            // uncomment below to test the property
            //modelInstance.collaboratorCanShare shouldBe ("TODO")
        }

        // to test the property `notifyOnNewAsset`
        should("test notifyOnNewAsset") {
            // uncomment below to test the property
            //modelInstance.notifyOnNewAsset shouldBe ("TODO")
        }

        // to test the property `notifyOnNewCollaborator`
        should("test notifyOnNewCollaborator") {
            // uncomment below to test the property
            //modelInstance.notifyOnNewCollaborator shouldBe ("TODO")
        }

        // to test the property `notifyOnNewComment`
        should("test notifyOnNewComment") {
            // uncomment below to test the property
            //modelInstance.notifyOnNewComment shouldBe ("TODO")
        }

        // to test the property `notifyOnUpdatedLabel`
        should("test notifyOnUpdatedLabel") {
            // uncomment below to test the property
            //modelInstance.notifyOnUpdatedLabel shouldBe ("TODO")
        }

        // to test the property `notifySlack`
        should("test notifySlack") {
            // uncomment below to test the property
            //modelInstance.notifySlack shouldBe ("TODO")
        }

    }
}
