/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dev.androidbroadcast.framesdk.models.ReviewLinkItem
import dev.androidbroadcast.framesdk.models.Asset
import dev.androidbroadcast.framesdk.models.ReviewLink

class ReviewLinkItemTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReviewLinkItem
        //val modelInstance = ReviewLinkItem()

        // to test the property `asset`
        should("test asset") {
            // uncomment below to test the property
            //modelInstance.asset shouldBe ("TODO")
        }

        // to test the property `assetId`
        should("test assetId") {
            // uncomment below to test the property
            //modelInstance.assetId shouldBe ("TODO")
        }

        // to test the property `deletedAt`
        should("test deletedAt") {
            // uncomment below to test the property
            //modelInstance.deletedAt shouldBe ("TODO")
        }

        // to test the property `index`
        should("test index") {
            // uncomment below to test the property
            //modelInstance.index shouldBe ("TODO")
        }

        // to test the property `insertedAt`
        should("test insertedAt") {
            // uncomment below to test the property
            //modelInstance.insertedAt shouldBe ("TODO")
        }

        // to test the property `reviewLink`
        should("test reviewLink") {
            // uncomment below to test the property
            //modelInstance.reviewLink shouldBe ("TODO")
        }

        // to test the property `reviewLinkId`
        should("test reviewLinkId") {
            // uncomment below to test the property
            //modelInstance.reviewLinkId shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

    }
}
