/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dev.androidbroadcast.framesdk.models.SessionWatermarkBlock
import dev.androidbroadcast.framesdk.models.SessionWatermarkDataPoint

class SessionWatermarkBlockTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SessionWatermarkBlock
        //val modelInstance = SessionWatermarkBlock()

        // to test the property `alpha`
        should("test alpha") {
            // uncomment below to test the property
            //modelInstance.alpha shouldBe ("TODO")
        }

        // to test the property `dataPoints`
        should("test dataPoints") {
            // uncomment below to test the property
            //modelInstance.dataPoints shouldBe ("TODO")
        }

        // to test the property `fontSize`
        should("test fontSize") {
            // uncomment below to test the property
            //modelInstance.fontSize shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `position`
        should("test position") {
            // uncomment below to test the property
            //modelInstance.position shouldBe ("TODO")
        }

        // to test the property `positionReferencePoint`
        should("test positionReferencePoint") {
            // uncomment below to test the property
            //modelInstance.positionReferencePoint shouldBe ("TODO")
        }

        // to test the property `positionX`
        should("test positionX") {
            // uncomment below to test the property
            //modelInstance.positionX shouldBe ("TODO")
        }

        // to test the property `positionY`
        should("test positionY") {
            // uncomment below to test the property
            //modelInstance.positionY shouldBe ("TODO")
        }

        // to test the property `scrollText`
        should("test scrollText") {
            // uncomment below to test the property
            //modelInstance.scrollText shouldBe ("TODO")
        }

        // to test the property `textAlignment`
        should("test textAlignment") {
            // uncomment below to test the property
            //modelInstance.textAlignment shouldBe ("TODO")
        }

        // to test the property `textColor`
        should("test textColor") {
            // uncomment below to test the property
            //modelInstance.textColor shouldBe ("TODO")
        }

        // to test the property `textShadow`
        should("test textShadow") {
            // uncomment below to test the property
            //modelInstance.textShadow shouldBe ("TODO")
        }

    }
}
