/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dev.androidbroadcast.framesdk.models.ShareableEntityAccessControl

class ShareableEntityAccessControlTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ShareableEntityAccessControl
        //val modelInstance = ShareableEntityAccessControl()

        // to test the property `inviteOnly`
        should("test inviteOnly") {
            // uncomment below to test the property
            //modelInstance.inviteOnly shouldBe ("TODO")
        }

    }
}
