/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dev.androidbroadcast.framesdk.models.TriggerRealtimeLoggingEventRequest
import dev.androidbroadcast.framesdk.models.SMPTETimeRepresentation

class TriggerRealtimeLoggingEventRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TriggerRealtimeLoggingEventRequest
        //val modelInstance = TriggerRealtimeLoggingEventRequest()

        // to test the property `actionType`
        should("test actionType") {
            // uncomment below to test the property
            //modelInstance.actionType shouldBe ("TODO")
        }

        // to test the property `offset`
        should("test offset") {
            // uncomment below to test the property
            //modelInstance.offset shouldBe ("TODO")
        }

        // to test the property `start`
        should("test start") {
            // uncomment below to test the property
            //modelInstance.start shouldBe ("TODO")
        }

        // to test the property `duration`
        should("test duration") {
            // uncomment below to test the property
            //modelInstance.duration shouldBe ("TODO")
        }

    }
}
