/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dev.androidbroadcast.framesdk.models.UserPermissions

class UserPermissionsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserPermissions
        //val modelInstance = UserPermissions()

        // to test the property `canDownload`
        should("test canDownload") {
            // uncomment below to test the property
            //modelInstance.canDownload shouldBe ("TODO")
        }

        // to test the property `canModifyTemplate`
        should("test canModifyTemplate") {
            // uncomment below to test the property
            //modelInstance.canModifyTemplate shouldBe ("TODO")
        }

        // to test the property `canPublicSharePresentation`
        should("test canPublicSharePresentation") {
            // uncomment below to test the property
            //modelInstance.canPublicSharePresentation shouldBe ("TODO")
        }

        // to test the property `canPublicShareReviewLink`
        should("test canPublicShareReviewLink") {
            // uncomment below to test the property
            //modelInstance.canPublicShareReviewLink shouldBe ("TODO")
        }

        // to test the property `canShareDownloadablePresentation`
        should("test canShareDownloadablePresentation") {
            // uncomment below to test the property
            //modelInstance.canShareDownloadablePresentation shouldBe ("TODO")
        }

        // to test the property `canShareDownloadableReviewLink`
        should("test canShareDownloadableReviewLink") {
            // uncomment below to test the property
            //modelInstance.canShareDownloadableReviewLink shouldBe ("TODO")
        }

        // to test the property `canShareUnwatermarkedPresentation`
        should("test canShareUnwatermarkedPresentation") {
            // uncomment below to test the property
            //modelInstance.canShareUnwatermarkedPresentation shouldBe ("TODO")
        }

        // to test the property `canShareUnwatermarkedReviewLink`
        should("test canShareUnwatermarkedReviewLink") {
            // uncomment below to test the property
            //modelInstance.canShareUnwatermarkedReviewLink shouldBe ("TODO")
        }

    }
}
