/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dev.androidbroadcast.framesdk.apis.NotificationsApi
import dev.androidbroadcast.framesdk.models.GetGroupedNotifications200Response

class NotificationsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NotificationsApi
        //val apiInstance = NotificationsApi()

        // to test getGroupedNotifications
        should("test getGroupedNotifications") {
            // uncomment below to test getGroupedNotifications
            //val result : GetGroupedNotifications200Response = apiInstance.getGroupedNotifications()
            //result shouldBe ("TODO")
        }

    }
}
