/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dev.androidbroadcast.framesdk.apis.PresentationsApi
import dev.androidbroadcast.framesdk.models.CreatePresentationRequest
import dev.androidbroadcast.framesdk.models.HTTPError
import dev.androidbroadcast.framesdk.models.Presentation
import dev.androidbroadcast.framesdk.models.UpdatePresentationRequest

class PresentationsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PresentationsApi
        //val apiInstance = PresentationsApi()

        // to test createPresentation
        should("test createPresentation") {
            // uncomment below to test createPresentation
            //val assetId : kotlin.String = eefb57e0-79f2-4bc7-9b70-99fbc175175c // kotlin.String | Asset ID
            //val createPresentationRequest : CreatePresentationRequest =  // CreatePresentationRequest | Presentation to create
            //val result : Presentation = apiInstance.createPresentation(assetId, createPresentationRequest)
            //result shouldBe ("TODO")
        }

        // to test deletePresentation
        should("test deletePresentation") {
            // uncomment below to test deletePresentation
            //val presentationId : kotlin.String = presentationId_example // kotlin.String | Presentation Link ID
            //val result : Presentation = apiInstance.deletePresentation(presentationId)
            //result shouldBe ("TODO")
        }

        // to test getAssetPresentations
        should("test getAssetPresentations") {
            // uncomment below to test getAssetPresentations
            //val assetId : kotlin.String = eefb57e0-79f2-4bc7-9b70-99fbc175175c // kotlin.String | Asset ID
            //val result : kotlin.collections.List<Presentation> = apiInstance.getAssetPresentations(assetId)
            //result shouldBe ("TODO")
        }

        // to test getProjectPresentations
        should("test getProjectPresentations") {
            // uncomment below to test getProjectPresentations
            //val projectId : kotlin.String = eefb57e0-79f2-4bc7-9b70-99fbc175175c // kotlin.String | Project ID
            //val result : kotlin.collections.List<Presentation> = apiInstance.getProjectPresentations(projectId)
            //result shouldBe ("TODO")
        }

        // to test getUserPresentations
        should("test getUserPresentations") {
            // uncomment below to test getUserPresentations
            //val result : kotlin.collections.List<Presentation> = apiInstance.getUserPresentations()
            //result shouldBe ("TODO")
        }

        // to test showPresentation
        should("test showPresentation") {
            // uncomment below to test showPresentation
            //val presentationId : kotlin.String = presentationId_example // kotlin.String | Presentation Link ID
            //val result : Presentation = apiInstance.showPresentation(presentationId)
            //result shouldBe ("TODO")
        }

        // to test updatePresentation
        should("test updatePresentation") {
            // uncomment below to test updatePresentation
            //val presentationId : kotlin.String = presentationId_example // kotlin.String | Presentation Link ID
            //val updatePresentationRequest : UpdatePresentationRequest =  // UpdatePresentationRequest | Presentation to update
            //val result : Presentation = apiInstance.updatePresentation(presentationId, updatePresentationRequest)
            //result shouldBe ("TODO")
        }

    }
}
