/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dev.androidbroadcast.framesdk.apis.PrivateApi
import dev.androidbroadcast.framesdk.models.AssetSubtitle
import dev.androidbroadcast.framesdk.models.GetGroupedNotifications200Response
import dev.androidbroadcast.framesdk.models.HTTPError

class PrivateApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PrivateApi
        //val apiInstance = PrivateApi()

        // to test getGroupedNotifications
        should("test getGroupedNotifications") {
            // uncomment below to test getGroupedNotifications
            //val result : GetGroupedNotifications200Response = apiInstance.getGroupedNotifications()
            //result shouldBe ("TODO")
        }

        // to test getSubtitles
        should("test getSubtitles") {
            // uncomment below to test getSubtitles
            //val assetId : kotlin.String = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.String | 
            //val result : AssetSubtitle = apiInstance.getSubtitles(assetId)
            //result shouldBe ("TODO")
        }

    }
}
