/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dev.androidbroadcast.framesdk.apis.SystemApi
import dev.androidbroadcast.framesdk.models.HealthCheck200Response

class SystemApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SystemApi
        //val apiInstance = SystemApi()

        // to test healthCheck
        should("test healthCheck") {
            // uncomment below to test healthCheck
            //val result : HealthCheck200Response = apiInstance.healthCheck()
            //result shouldBe ("TODO")
        }

    }
}
