/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import dev.androidbroadcast.framesdk.models.AccountMember
import dev.androidbroadcast.framesdk.models.Plan
import dev.androidbroadcast.framesdk.models.Subscription
import dev.androidbroadcast.framesdk.models.Team
import dev.androidbroadcast.framesdk.models.User
import dev.androidbroadcast.framesdk.models.Watermark

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param invoiceEmails 
 * @param city 
 * @param accountDefaultColor 
 * @param companyName 
 * @param storage 
 * @param fileCount 
 * @param owner 
 * @param uploadUrl 
 * @param deletedAt 
 * @param line1 
 * @param postalCode 
 * @param vat 
 * @param companyAddress 
 * @param lifetimeFileCount 
 * @param state 
 * @param teams 
 * @param image64 
 * @param archivedStorage 
 * @param image128 
 * @param ownerId 
 * @param userCount 
 * @param lockedAt 
 * @param image 
 * @param teamCount 
 * @param collaboratorRoleCount 
 * @param billingEmails 
 * @param image32 
 * @param unpaidAt 
 * @param insertedAt 
 * @param updatedAt 
 * @param projectCount 
 * @param duration 
 * @param delinquentAt 
 * @param collaboratorCount 
 * @param plan 
 * @param watermark 
 * @param folderCount 
 * @param id 
 * @param displayName 
 * @param country 
 * @param subscription 
 * @param accountMembers 
 * @param frames 
 * @param memberCount 
 * @param image256 
 */
@Serializable

data class Account (

    @SerialName(value = "invoice_emails") val invoiceEmails: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "city") val city: kotlin.String? = null,

    @SerialName(value = "account_default_color") val accountDefaultColor: kotlin.String? = null,

    @SerialName(value = "company_name") val companyName: kotlin.String? = null,

    @SerialName(value = "storage") val storage: kotlin.Int? = null,

    @SerialName(value = "file_count") val fileCount: kotlin.Int? = null,

    @SerialName(value = "owner") val owner: User? = null,

    @SerialName(value = "upload_url") val uploadUrl: kotlin.String? = null,

    @SerialName(value = "deleted_at") val deletedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "line1") val line1: kotlin.String? = null,

    @SerialName(value = "postal_code") val postalCode: kotlin.String? = null,

    @SerialName(value = "vat") val vat: kotlin.String? = null,

    @SerialName(value = "company_address") val companyAddress: kotlin.String? = null,

    @SerialName(value = "lifetime_file_count") val lifetimeFileCount: kotlin.Int? = null,

    @SerialName(value = "state") val state: kotlin.String? = null,

    @SerialName(value = "teams") val teams: kotlin.collections.List<Team>? = null,

    @SerialName(value = "image_64") val image64: kotlin.String? = null,

    @SerialName(value = "archived_storage") val archivedStorage: kotlin.Int? = null,

    @SerialName(value = "image_128") val image128: kotlin.String? = null,

    @SerialName(value = "owner_id") val ownerId: kotlin.String? = null,

    @SerialName(value = "user_count") val userCount: kotlin.Int? = null,

    @SerialName(value = "locked_at") val lockedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "image") val image: kotlin.String? = null,

    @SerialName(value = "team_count") val teamCount: kotlin.Int? = null,

    @SerialName(value = "collaborator_role_count") val collaboratorRoleCount: kotlin.Int? = null,

    @SerialName(value = "billing_emails") val billingEmails: kotlin.String? = null,

    @SerialName(value = "image_32") val image32: kotlin.String? = null,

    @SerialName(value = "unpaid_at") val unpaidAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "inserted_at") val insertedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "updated_at") val updatedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "project_count") val projectCount: kotlin.Int? = null,

    @SerialName(value = "duration") val duration: kotlin.Int? = null,

    @SerialName(value = "delinquent_at") val delinquentAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "collaborator_count") val collaboratorCount: kotlin.Int? = null,

    @SerialName(value = "plan") val plan: Plan? = null,

    @SerialName(value = "watermark") val watermark: Watermark? = null,

    @SerialName(value = "folder_count") val folderCount: kotlin.Int? = null,

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "display_name") val displayName: kotlin.String? = null,

    @SerialName(value = "country") val country: kotlin.String? = null,

    @SerialName(value = "subscription") val subscription: Subscription? = null,

    @SerialName(value = "account_members") val accountMembers: kotlin.collections.List<AccountMember>? = null,

    @SerialName(value = "frames") val frames: kotlin.Int? = null,

    @SerialName(value = "member_count") val memberCount: kotlin.Int? = null,

    @SerialName(value = "image_256") val image256: kotlin.String? = null

) {


}

