/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import dev.androidbroadcast.framesdk.models.Team
import dev.androidbroadcast.framesdk.models.Webhook

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param active 
 * @param allowCollaborators 
 * @param creatorId 
 * @param deletedAt 
 * @param description 
 * @param event 
 * @param id 
 * @param image 
 * @param insertedAt 
 * @param name 
 * @param team 
 * @param teamId 
 * @param updatedAt 
 * @param uploadUrl 
 * @param url 
 * @param webhook 
 */
@Serializable

data class Action (

    @SerialName(value = "active") val active: kotlin.Boolean? = null,

    @SerialName(value = "allow_collaborators") val allowCollaborators: kotlin.Boolean? = null,

    @SerialName(value = "creator_id") val creatorId: kotlin.String? = null,

    @SerialName(value = "deleted_at") val deletedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "event") val event: kotlin.String? = null,

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "image") val image: kotlin.String? = null,

    @SerialName(value = "inserted_at") val insertedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "team") val team: Team? = null,

    @SerialName(value = "team_id") val teamId: kotlin.String? = null,

    @SerialName(value = "updated_at") val updatedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "upload_url") val uploadUrl: kotlin.String? = null,

    @SerialName(value = "url") val url: kotlin.String? = null,

    @SerialName(value = "webhook") val webhook: Webhook? = null

) {


}

