/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import dev.androidbroadcast.framesdk.models.ProjectPreferences

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param deletedAt 
 * @param email 
 * @param id 
 * @param insertedAt 
 * @param name 
 * @param notificationPreferences 
 * @param updatedAt 
 * @param userDefaultColor 
 */
@Serializable

data class AnonymousUser (

    @SerialName(value = "deleted_at") val deletedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "email") val email: kotlin.String? = null,

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "inserted_at") val insertedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "notification_preferences") val notificationPreferences: ProjectPreferences? = null,

    @SerialName(value = "updated_at") val updatedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "user_default_color") val userDefaultColor: kotlin.String? = null

) {


}

