/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param error 
 */
@Serializable

data class AuthDeviceConfirmDevice400Response (

    @SerialName(value = "error") @Required val error: AuthDeviceConfirmDevice400Response.Error

) {

    /**
     * 
     *
     * Values: authorization_pending,expired_token,invalid_grant,invalid_client,invalid_request,slow_down
     */
    @Serializable
    enum class Error(val value: kotlin.String) {
        @SerialName(value = "authorization_pending") authorization_pending("authorization_pending"),
        @SerialName(value = "expired_token") expired_token("expired_token"),
        @SerialName(value = "invalid_grant") invalid_grant("invalid_grant"),
        @SerialName(value = "invalid_client") invalid_client("invalid_client"),
        @SerialName(value = "invalid_request") invalid_request("invalid_request"),
        @SerialName(value = "slow_down") slow_down("slow_down");
    }

}

