/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import dev.androidbroadcast.framesdk.models.BatchCopyAssetRequestBatchInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param batch 
 * @param copyComments 
 */
@Serializable

data class BatchCopyAssetRequest (

    @SerialName(value = "batch") val batch: kotlin.collections.List<BatchCopyAssetRequestBatchInner>? = null,

    @SerialName(value = "copy_comments") val copyComments: BatchCopyAssetRequest.CopyComments? = null

) {

    /**
     * 
     *
     * Values: all,none
     */
    @Serializable
    enum class CopyComments(val value: kotlin.String) {
        @SerialName(value = "all") all("all"),
        @SerialName(value = "none") none("none");
    }

}

