/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import dev.androidbroadcast.framesdk.models.BatchInviteParamsBatchInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param batch 
 * @param defaultMessage Default invite message to be applied to all invites created
 * @param sendEmail When false no emails will be sent to the new Reviewers and Pending Reviewers
 */
@Serializable

data class BatchInviteParams (

    @SerialName(value = "batch") val batch: kotlin.collections.List<BatchInviteParamsBatchInner>? = null,

    /* Default invite message to be applied to all invites created */
    @SerialName(value = "default_message") val defaultMessage: kotlin.String? = null,

    /* When false no emails will be sent to the new Reviewers and Pending Reviewers */
    @SerialName(value = "send_email") val sendEmail: kotlin.Boolean? = true

) {


}

