/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import dev.androidbroadcast.framesdk.models.BatchDeleteCollaboratorsRequestBatchInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param batch 
 */
@Serializable

data class BatchDeleteCollaboratorsRequest (

    @SerialName(value = "batch") @Required val batch: kotlin.collections.Set<BatchDeleteCollaboratorsRequestBatchInner>

) {


}

