/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param email Create an invite for the given email
 * @param message Invite message to be used for this one bath op
 * @param teamId Create a set of invites for all approved team members within the given team
 * @param userGroupId Create a set of invites for all the users within the given user group
 * @param userId Create an invite for the given user_id
 */
@Serializable

data class BatchInviteParamsBatchInner (

    /* Create an invite for the given email */
    @SerialName(value = "email") val email: kotlin.String? = null,

    /* Invite message to be used for this one bath op */
    @SerialName(value = "message") val message: kotlin.String? = null,

    /* Create a set of invites for all approved team members within the given team */
    @SerialName(value = "team_id") val teamId: kotlin.String? = null,

    /* Create a set of invites for all the users within the given user group */
    @SerialName(value = "user_group_id") val userGroupId: kotlin.String? = null,

    /* Create an invite for the given user_id */
    @SerialName(value = "user_id") val userId: kotlin.String? = null

) {


}

