/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import dev.androidbroadcast.framesdk.models.User

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param type 
 * @param email 
 * @param projectId 
 * @param user 
 * @param userId 
 */
@Serializable

data class Collaborator (

    @SerialName(value = "_type") val type: Collaborator.Type? = null,

    @SerialName(value = "email") val email: kotlin.String? = null,

    @SerialName(value = "project_id") val projectId: kotlin.String? = null,

    @SerialName(value = "user") val user: User? = null,

    @SerialName(value = "user_id") val userId: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: collaborator,pending_collaborator
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "collaborator") collaborator("collaborator"),
        @SerialName(value = "pending_collaborator") pending_collaborator("pending_collaborator");
    }

}

