/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import dev.androidbroadcast.framesdk.models.User

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param assetId 
 * @param count 
 * @param deletedAt 
 * @param id 
 * @param insertedAt 
 * @param reviewLinkId 
 * @param type 
 * @param updatedAt 
 * @param user 
 * @param userId 
 */
@Serializable

data class CommentImpression (

    @SerialName(value = "asset_id") val assetId: kotlin.String? = null,

    @SerialName(value = "count") val count: kotlin.Int? = null,

    @SerialName(value = "deleted_at") val deletedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "inserted_at") val insertedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "review_link_id") val reviewLinkId: kotlin.String? = null,

    @SerialName(value = "type") val type: kotlin.String? = null,

    @SerialName(value = "updated_at") val updatedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "user") val user: User? = null,

    @SerialName(value = "user_id") val userId: kotlin.String? = null

) {


}

