/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import dev.androidbroadcast.framesdk.models.ProjectPreferences

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param name Project name
 * @param `private` If true, the project is private to the creating user
 * @param projectPreferences 
 */
@Serializable

data class CreateProjectRequest (

    /* Project name */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* If true, the project is private to the creating user */
    @SerialName(value = "private") val `private`: kotlin.Boolean? = null,

    @SerialName(value = "project_preferences") val projectPreferences: ProjectPreferences? = null

) {


}

