/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param code 
 * @param detail 
 * @param status 
 * @param title 
 */
@Serializable

data class DeviceAssetCreateDeprecated409ResponseErrorsInner (

    @SerialName(value = "code") @Required val code: DeviceAssetCreateDeprecated409ResponseErrorsInner.Code,

    @SerialName(value = "detail") @Required val detail: kotlin.String,

    @SerialName(value = "status") @Required val status: DeviceAssetCreateDeprecated409ResponseErrorsInner.Status,

    @SerialName(value = "title") @Required val title: kotlin.String

) {

    /**
     * 
     *
     * Values: _409
     */
    @Serializable
    enum class Code(val value: kotlin.Double) {
        @SerialName(value = "409.0") _409(409.0);
    }
    /**
     * 
     *
     * Values: _409
     */
    @Serializable
    enum class Status(val value: kotlin.Double) {
        @SerialName(value = "409.0") _409(409.0);
    }

}

