/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param deviceCode The device code should be hidden from the user, and is used to identify this authorization request when polling to see if the user has entered their code successfully.
 * @param expiresIn The number of seconds until this code expires.
 * @param interval How long the we should wait between polling requests to see if the user has entered the code.
 * @param name The name of the device we are trying to connect.
 * @param userCode The six-digit code the user will enter into Frame.io to pair the device to a project.
 */
@Serializable

data class DeviceRequestCode200Response (

    /* The device code should be hidden from the user, and is used to identify this authorization request when polling to see if the user has entered their code successfully. */
    @SerialName(value = "device_code") @Required val deviceCode: kotlin.String,

    /* The number of seconds until this code expires. */
    @SerialName(value = "expires_in") @Required val expiresIn: kotlin.Double,

    /* How long the we should wait between polling requests to see if the user has entered the code. */
    @SerialName(value = "interval") @Required val interval: kotlin.Double,

    /* The name of the device we are trying to connect. */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* The six-digit code the user will enter into Frame.io to pair the device to a project. */
    @SerialName(value = "user_code") @Required val userCode: kotlin.String

) {


}

