/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import dev.androidbroadcast.framesdk.models.DeviceAssetCreateDeprecated409ResponseErrorsInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param code 
 * @param errors 
 * @param message 
 */
@Serializable

data class DeviceAssetCreateDeprecated409Response (

    @SerialName(value = "code") @Required val code: DeviceAssetCreateDeprecated409Response.Code,

    @SerialName(value = "errors") @Required val errors: kotlin.collections.Set<DeviceAssetCreateDeprecated409ResponseErrorsInner>,

    @SerialName(value = "message") @Required val message: DeviceAssetCreateDeprecated409Response.Message

) {

    /**
     * 
     *
     * Values: _409
     */
    @Serializable
    enum class Code(val value: kotlin.Double) {
        @SerialName(value = "409.0") _409(409.0);
    }
    /**
     * 
     *
     * Values: Channel_Paused,invalid_client,slow_down
     */
    @Serializable
    enum class Message(val value: kotlin.String) {
        @SerialName(value = "Channel Paused") Channel_Paused("Channel Paused"),
        @SerialName(value = "invalid_client") invalid_client("invalid_client"),
        @SerialName(value = "slow_down") slow_down("slow_down");
    }

}

