/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param type The type of the text element
 * @param format 
 * @param `value` 
 * @param textElement The type of the text element
 */
@Serializable

data class GetGroupedNotifications200ResponseTextElementsHeaderInner (

    /* The type of the text element */
    @SerialName(value = "type") val type: GetGroupedNotifications200ResponseTextElementsHeaderInner.Type? = null,

    @SerialName(value = "format") val format: GetGroupedNotifications200ResponseTextElementsHeaderInner.Format? = null,

    @SerialName(value = "value") val `value`: kotlin.String? = null,

    /* The type of the text element */
    @SerialName(value = "text_element") val textElement: GetGroupedNotifications200ResponseTextElementsHeaderInner.TextElement? = null

) {

    /**
     * The type of the text element
     *
     * Values: text_element
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "text_element") text_element("text_element");
    }
    /**
     * 
     *
     * Values: strong,plain_text
     */
    @Serializable
    enum class Format(val value: kotlin.String) {
        @SerialName(value = "strong") strong("strong"),
        @SerialName(value = "plain_text") plain_text("plain_text");
    }
    /**
     * The type of the text element
     *
     * Values: text_element
     */
    @Serializable
    enum class TextElement(val value: kotlin.String) {
        @SerialName(value = "text_element") text_element("text_element");
    }

}

