/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param type 
 * @param id 
 */
@Serializable

data class GetGroupedNotifications200ResponseLinkToInner (

    @SerialName(value = "type") val type: GetGroupedNotifications200ResponseLinkToInner.Type? = null,

    @SerialName(value = "id") val id: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: asset,comment
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "asset") asset("asset"),
        @SerialName(value = "comment") comment("comment");
    }

}

