/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import dev.androidbroadcast.framesdk.models.GetProjectCollaborators201ResponseInnerUserProjectRole
import dev.androidbroadcast.framesdk.models.GetProjectCollaborators201ResponseInnerUserRoles

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param name 
 * @param userDefaultColor 
 * @param type 
 * @param digestFrequency 
 * @param insertedAt 
 * @param image32 
 * @param profileImage 
 * @param timezoneValue 
 * @param updatedAt 
 * @param projectRole 
 * @param firstLoginAt 
 * @param mfaEnforcedAt 
 * @param roles 
 * @param image128 
 * @param email 
 * @param image256 
 * @param joinedVia 
 * @param id 
 * @param image64 
 * @param lastSeen 
 * @param uploadUrl 
 * @param accountId 
 * @param nextDigestDate 
 * @param fromGoogle 
 * @param phone 
 * @param location 
 * @param emailConfirmBy 
 * @param context 
 * @param profileImageOriginal 
 * @param deletedAt 
 * @param featuresSeen 
 * @param bio 
 * @param emailPreferences 
 */
@Serializable

data class GetProjectCollaborators201ResponseInnerUser (

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "user_default_color") @Required val userDefaultColor: kotlin.String,

    @SerialName(value = "_type") @Required val type: kotlin.String,

    @SerialName(value = "digest_frequency") @Required val digestFrequency: kotlin.String,

    @SerialName(value = "inserted_at") @Required val insertedAt: kotlin.String,

    @SerialName(value = "image_32") @Required val image32: kotlin.String,

    @SerialName(value = "profile_image") @Required val profileImage: kotlin.String,

    @SerialName(value = "timezone_value") @Required val timezoneValue: kotlin.String,

    @SerialName(value = "updated_at") @Required val updatedAt: kotlin.String,

    @SerialName(value = "project_role") @Required val projectRole: GetProjectCollaborators201ResponseInnerUserProjectRole,

    @SerialName(value = "first_login_at") @Required val firstLoginAt: kotlin.String,

    @SerialName(value = "mfa_enforced_at") @Required val mfaEnforcedAt: kotlin.String,

    @SerialName(value = "roles") @Required val roles: GetProjectCollaborators201ResponseInnerUserRoles,

    @SerialName(value = "image_128") @Required val image128: kotlin.String,

    @SerialName(value = "email") @Required val email: kotlin.String,

    @SerialName(value = "image_256") @Required val image256: kotlin.String,

    @SerialName(value = "joined_via") @Required val joinedVia: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "image_64") @Required val image64: kotlin.String,

    @SerialName(value = "last_seen") @Required val lastSeen: kotlin.String,

    @SerialName(value = "upload_url") @Required val uploadUrl: kotlin.String,

    @SerialName(value = "account_id") @Required val accountId: kotlin.String,

    @SerialName(value = "next_digest_date") @Required val nextDigestDate: kotlin.String,

    @SerialName(value = "from_google") @Required val fromGoogle: kotlin.Boolean,

    @SerialName(value = "phone") val phone: kotlin.Any? = null,

    @SerialName(value = "location") val location: kotlin.Any? = null,

    @SerialName(value = "email_confirm_by") val emailConfirmBy: kotlin.Any? = null,

    @SerialName(value = "context") val context: kotlin.Any? = null,

    @SerialName(value = "profile_image_original") val profileImageOriginal: kotlin.Any? = null,

    @SerialName(value = "deleted_at") val deletedAt: kotlin.Any? = null,

    @SerialName(value = "features_seen") val featuresSeen: kotlin.Any? = null,

    @SerialName(value = "bio") val bio: kotlin.Any? = null,

    @SerialName(value = "email_preferences") val emailPreferences: kotlin.Any? = null

) {


}

