/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param admin 
 * @param id 
 * @param sales 
 * @param support 
 */
@Serializable

data class GetProjectCollaborators201ResponseInnerUserRoles (

    @SerialName(value = "admin") @Required val admin: kotlin.Boolean,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "sales") @Required val sales: kotlin.Boolean,

    @SerialName(value = "support") @Required val support: kotlin.Boolean

) {


}

