/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param collaborator 
 * @param owner 
 * @param teamMember 
 * @param teamRole 
 */
@Serializable

data class GetProjectCollaborators201ResponseInnerUserProjectRole (

    @SerialName(value = "collaborator") @Required val collaborator: kotlin.Boolean,

    @SerialName(value = "owner") @Required val owner: kotlin.Boolean,

    @SerialName(value = "team_member") @Required val teamMember: kotlin.Boolean,

    @SerialName(value = "team_role") val teamRole: kotlin.Any? = null

) {


}

