/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import dev.androidbroadcast.framesdk.models.GetProjectCollaborators201ResponseInnerUser

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param type 
 * @param creatorId 
 * @param id 
 * @param insertedAt 
 * @param projectId 
 * @param updatedAt 
 * @param user 
 * @param userId 
 * @param deletedAt 
 * @param message 
 */
@Serializable

data class GetProjectCollaborators201ResponseInner (

    @SerialName(value = "_type") @Required val type: kotlin.String,

    @SerialName(value = "creator_id") @Required val creatorId: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "inserted_at") @Required val insertedAt: kotlin.String,

    @SerialName(value = "project_id") @Required val projectId: kotlin.String,

    @SerialName(value = "updated_at") @Required val updatedAt: kotlin.String,

    @SerialName(value = "user") @Required val user: GetProjectCollaborators201ResponseInnerUser,

    @SerialName(value = "user_id") @Required val userId: kotlin.String,

    @SerialName(value = "deleted_at") val deletedAt: kotlin.Any? = null,

    @SerialName(value = "message") val message: kotlin.Any? = null

) {


}

