/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param code 
 * @param detail 
 * @param status 
 * @param title 
 */
@Serializable

data class HTTPErrorErrorsInner (

    @SerialName(value = "code") val code: kotlin.Int? = null,

    @SerialName(value = "detail") val detail: kotlin.String? = null,

    @SerialName(value = "status") val status: kotlin.Int? = null,

    @SerialName(value = "title") val title: kotlin.String? = null

) {


}

