/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import dev.androidbroadcast.framesdk.models.HTTPErrorErrorsInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param code 
 * @param errors 
 * @param message 
 */
@Serializable

data class HTTPError (

    @SerialName(value = "code") val code: kotlin.Int? = null,

    @SerialName(value = "errors") val errors: kotlin.collections.List<HTTPErrorErrorsInner>? = null,

    @SerialName(value = "message") val message: kotlin.String? = null

) {


}

