/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param bucket 
 * @param key 
 * @param type 
 * @param uploaded 
 */
@Serializable

data class Image (

    @SerialName(value = "bucket") val bucket: kotlin.String? = null,

    @SerialName(value = "key") val key: kotlin.String? = null,

    @SerialName(value = "type") val type: kotlin.String? = "image/jpeg",

    @SerialName(value = "uploaded") val uploaded: kotlin.Boolean? = false

) {


}

