/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param is360 
 * @param isHdr 
 * @param isOriginalPlayerCompatible 
 */
@Serializable

data class MetadataFlags (

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "is_360") val is360: kotlin.Boolean? = null,

    @SerialName(value = "is_hdr") val isHdr: kotlin.Boolean? = null,

    @SerialName(value = "is_original_player_compatible") val isOriginalPlayerCompatible: kotlin.Boolean? = null

) {


}

