/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import dev.androidbroadcast.framesdk.models.AvailableFeatures

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param archivedStorageLimit 
 * @param autoscaling 
 * @param availableFeatures 
 * @param collaboratorLimit 
 * @param cost 
 * @param defaultPlan 
 * @param deletedAt 
 * @param enterprise 
 * @param fileLimit 
 * @param id 
 * @param insertedAt 
 * @param lifetimeFileLimit 
 * @param memberLimit 
 * @param name 
 * @param paymentMethod 
 * @param period 
 * @param projectLimit 
 * @param storageLimit 
 * @param teamLimit 
 * @param tier 
 * @param title 
 * @param updatedAt 
 * @param userLimit 
 * @param userMax 
 * @param version 
 */
@Serializable

data class Plan (

    @SerialName(value = "archived_storage_limit") val archivedStorageLimit: kotlin.Int? = null,

    @SerialName(value = "autoscaling") val autoscaling: kotlin.Boolean? = null,

    @SerialName(value = "available_features") val availableFeatures: AvailableFeatures? = null,

    @SerialName(value = "collaborator_limit") val collaboratorLimit: kotlin.Int? = null,

    @SerialName(value = "cost") val cost: kotlin.Int? = null,

    @SerialName(value = "default_plan") val defaultPlan: kotlin.Boolean? = null,

    @SerialName(value = "deleted_at") val deletedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "enterprise") val enterprise: kotlin.Boolean? = null,

    @SerialName(value = "file_limit") val fileLimit: kotlin.Int? = null,

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "inserted_at") val insertedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "lifetime_file_limit") val lifetimeFileLimit: kotlin.Int? = null,

    @SerialName(value = "member_limit") val memberLimit: kotlin.Int? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "payment_method") val paymentMethod: Plan.PaymentMethod? = null,

    @SerialName(value = "period") val period: Plan.Period? = null,

    @SerialName(value = "project_limit") val projectLimit: kotlin.Int? = null,

    @SerialName(value = "storage_limit") val storageLimit: kotlin.Int? = null,

    @SerialName(value = "team_limit") val teamLimit: kotlin.Int? = null,

    @SerialName(value = "tier") val tier: Plan.Tier? = null,

    @SerialName(value = "title") val title: kotlin.String? = null,

    @SerialName(value = "updated_at") val updatedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "user_limit") val userLimit: kotlin.Int? = null,

    @SerialName(value = "user_max") val userMax: kotlin.Int? = null,

    @SerialName(value = "version") val version: kotlin.Int? = null

) {

    /**
     * 
     *
     * Values: stripe,check
     */
    @Serializable
    enum class PaymentMethod(val value: kotlin.String) {
        @SerialName(value = "stripe") stripe("stripe"),
        @SerialName(value = "check") check("check");
    }
    /**
     * 
     *
     * Values: monthly,yearly,semiannually
     */
    @Serializable
    enum class Period(val value: kotlin.String) {
        @SerialName(value = "monthly") monthly("monthly"),
        @SerialName(value = "yearly") yearly("yearly"),
        @SerialName(value = "semiannually") semiannually("semiannually");
    }
    /**
     * 
     *
     * Values: free,starter,pro,team,business,enterprise
     */
    @Serializable
    enum class Tier(val value: kotlin.String) {
        @SerialName(value = "free") free("free"),
        @SerialName(value = "starter") starter("starter"),
        @SerialName(value = "pro") pro("pro"),
        @SerialName(value = "team") team("team"),
        @SerialName(value = "business") business("business"),
        @SerialName(value = "enterprise") enterprise("enterprise");
    }

}

