/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import dev.androidbroadcast.framesdk.models.Asset
import dev.androidbroadcast.framesdk.models.PresentationItem
import dev.androidbroadcast.framesdk.models.Project
import dev.androidbroadcast.framesdk.models.ShareableEntityAccessControl
import dev.androidbroadcast.framesdk.models.Team

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param enabled 
 * @param vanity 
 * @param includeUploadDate 
 * @param presentationItems 
 * @param availableFeatures 
 * @param autoplay 
 * @param accessControl 
 * @param secure 
 * @param assetId 
 * @param projectId 
 * @param includeExt 
 * @param layout 
 * @param assets 
 * @param description 
 * @param deletedAt 
 * @param password 
 * @param asset 
 * @param team 
 * @param name 
 * @param format 
 * @param ownerId 
 * @param canDownload 
 * @param project 
 * @param shortUrl 
 * @param insertedAt 
 * @param updatedAt 
 * @param style 
 * @param textColor 
 * @param title 
 * @param expiresAt 
 * @param color 
 * @param id 
 * @param viewCount 
 * @param reviewerCount 
 * @param backgroundColor 
 */
@Serializable

data class Presentation (

    @SerialName(value = "enabled") val enabled: kotlin.Boolean? = null,

    @SerialName(value = "vanity") val vanity: kotlin.String? = null,

    @SerialName(value = "include_upload_date") val includeUploadDate: kotlin.Boolean? = null,

    @SerialName(value = "presentation_items") val presentationItems: kotlin.collections.List<PresentationItem>? = null,

    @SerialName(value = "available_features") val availableFeatures: kotlin.String? = null,

    @SerialName(value = "autoplay") val autoplay: kotlin.Boolean? = null,

    @SerialName(value = "access_control") val accessControl: ShareableEntityAccessControl? = null,

    @SerialName(value = "secure") val secure: kotlin.Boolean? = null,

    @SerialName(value = "asset_id") val assetId: kotlin.String? = null,

    @SerialName(value = "project_id") val projectId: kotlin.String? = null,

    @SerialName(value = "include_ext") val includeExt: kotlin.Boolean? = null,

    @SerialName(value = "layout") val layout: Presentation.Layout? = null,

    @SerialName(value = "assets") val assets: kotlin.collections.List<Asset>? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "deleted_at") val deletedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "password") val password: kotlin.String? = null,

    @SerialName(value = "asset") val asset: Asset? = null,

    @SerialName(value = "team") val team: Team? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "format") val format: kotlin.String? = null,

    @SerialName(value = "owner_id") val ownerId: kotlin.String? = null,

    @SerialName(value = "can_download") val canDownload: kotlin.Boolean? = null,

    @SerialName(value = "project") val project: Project? = null,

    @SerialName(value = "short_url") val shortUrl: kotlin.String? = null,

    @SerialName(value = "inserted_at") val insertedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "updated_at") val updatedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "style") val style: kotlin.String? = null,

    @SerialName(value = "text_color") val textColor: kotlin.String? = null,

    @SerialName(value = "title") val title: kotlin.String? = null,

    @SerialName(value = "expires_at") val expiresAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "color") val color: kotlin.String? = null,

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "view_count") val viewCount: kotlin.Int? = 0,

    @SerialName(value = "reviewer_count") val reviewerCount: kotlin.Int? = 0,

    @SerialName(value = "background_color") val backgroundColor: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: blog,reel
     */
    @Serializable
    enum class Layout(val value: kotlin.String) {
        @SerialName(value = "blog") blog("blog"),
        @SerialName(value = "reel") reel("reel");
    }

}

