/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param type 
 * @param id 
 * @param actorId 
 * @param assetType 
 * @param deviceId 
 * @param externalIndex 
 * @param insertedAt 
 * @param name Auto-generated name, based on the device model
 * @param projectId The Project ID that this device is linked to
 * @param projectDeviceId 
 * @param realTimeLoggingCapable 
 * @param status 
 * @param updatedAt 
 */
@Serializable

data class ProjectDeviceChannel (

    @SerialName(value = "_type") val type: kotlin.String? = "project_device_channel",

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "actor_id") val actorId: kotlin.String? = null,

    @SerialName(value = "asset_type") val assetType: ProjectDeviceChannel.AssetType? = null,

    @SerialName(value = "device_id") val deviceId: kotlin.String? = null,

    @SerialName(value = "external_index") val externalIndex: kotlin.Double? = null,

    @SerialName(value = "inserted_at") val insertedAt: kotlinx.datetime.Instant? = null,

    /* Auto-generated name, based on the device model */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* The Project ID that this device is linked to */
    @SerialName(value = "project_id") val projectId: kotlin.String? = null,

    @SerialName(value = "project_device_id") val projectDeviceId: kotlin.String? = null,

    @SerialName(value = "real_time_logging_capable") val realTimeLoggingCapable: kotlin.Boolean? = false,

    @SerialName(value = "status") val status: ProjectDeviceChannel.Status? = null,

    @SerialName(value = "updated_at") val updatedAt: kotlinx.datetime.Instant? = null

) {

    /**
     * 
     *
     * Values: audio,video,`data`
     */
    @Serializable
    enum class AssetType(val value: kotlin.String) {
        @SerialName(value = "audio") audio("audio"),
        @SerialName(value = "video") video("video"),
        @SerialName(value = "data") `data`("data");
    }
    /**
     * 
     *
     * Values: offline,online
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "offline") offline("offline"),
        @SerialName(value = "online") online("online");
    }

}

