/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param collaboratorCanDownload 
 * @param collaboratorCanInvite 
 * @param collaboratorCanShare 
 * @param notifyOnNewAsset 
 * @param notifyOnNewCollaborator 
 * @param notifyOnNewComment 
 * @param notifyOnUpdatedLabel 
 * @param notifySlack 
 */
@Serializable

data class ProjectPreferences (

    @SerialName(value = "collaborator_can_download") val collaboratorCanDownload: kotlin.Boolean? = null,

    @SerialName(value = "collaborator_can_invite") val collaboratorCanInvite: kotlin.Boolean? = null,

    @SerialName(value = "collaborator_can_share") val collaboratorCanShare: kotlin.Boolean? = null,

    @SerialName(value = "notify_on_new_asset") val notifyOnNewAsset: kotlin.Boolean? = null,

    @SerialName(value = "notify_on_new_collaborator") val notifyOnNewCollaborator: kotlin.Boolean? = null,

    @SerialName(value = "notify_on_new_comment") val notifyOnNewComment: kotlin.Boolean? = null,

    @SerialName(value = "notify_on_updated_label") val notifyOnUpdatedLabel: kotlin.Boolean? = null,

    @SerialName(value = "notify_slack") val notifySlack: kotlin.Boolean? = null

) {


}

