/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import dev.androidbroadcast.framesdk.models.Project
import dev.androidbroadcast.framesdk.models.ProjectDeviceAssetType
import dev.androidbroadcast.framesdk.models.ProjectDeviceAuthorization
import dev.androidbroadcast.framesdk.models.ProjectDeviceChannel

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Represents the correlation between a physical device and a Frame.io project.
 *
 * @param id 
 * @param assetType 
 * @param creatorId 
 * @param deletedAt 
 * @param deviceId 
 * @param insertedAt 
 * @param lastSeenAt 
 * @param name Name of this device as shown in the iOS app and web app
 * @param projectId The Project ID that this device is linked to
 * @param updatedAt 
 * @param status 
 * @param timezone 
 * @param authorization 
 * @param project 
 * @param channels 
 * @param channelCount 
 * @param pathAssetType 
 * @param pathName 
 * @param requiredMetadataAttributes 
 */
@Serializable

data class ProjectDevice (

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "asset_type") val assetType: ProjectDeviceAssetType? = null,

    @SerialName(value = "creator_id") val creatorId: kotlin.String? = null,

    @SerialName(value = "deleted_at") val deletedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "device_id") val deviceId: kotlin.String? = null,

    @SerialName(value = "inserted_at") val insertedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "last_seen_at") val lastSeenAt: kotlinx.datetime.Instant? = null,

    /* Name of this device as shown in the iOS app and web app */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* The Project ID that this device is linked to */
    @SerialName(value = "project_id") val projectId: kotlin.String? = null,

    @SerialName(value = "updated_at") val updatedAt: kotlin.String? = null,

    @SerialName(value = "status") val status: ProjectDevice.Status? = null,

    @SerialName(value = "timezone") val timezone: kotlin.String? = null,

    @SerialName(value = "authorization") val authorization: ProjectDeviceAuthorization? = null,

    @SerialName(value = "project") val project: Project? = null,

    @SerialName(value = "channels") val channels: kotlin.collections.List<ProjectDeviceChannel>? = null,

    @SerialName(value = "channel_count") val channelCount: kotlin.Int? = null,

    @SerialName(value = "path_asset_type") val pathAssetType: kotlin.String? = null,

    @SerialName(value = "path_name") val pathName: kotlin.String? = null,

    @SerialName(value = "required_metadata_attributes") val requiredMetadataAttributes: kotlin.collections.List<kotlin.String>? = null

) {

    /**
     * 
     *
     * Values: offline,online
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "offline") offline("offline"),
        @SerialName(value = "online") online("online");
    }

}

