/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import dev.androidbroadcast.framesdk.models.ProjectDeviceAuthorizationAuthorizationCreator
import dev.androidbroadcast.framesdk.models.ProjectDeviceAuthorizationAuthorizationScopes

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param type 
 * @param creator 
 * @param creatorId 
 * @param id 
 * @param insertedAt 
 * @param projectDeviceId 
 * @param scopes 
 * @param expiresAt 
 */
@Serializable

data class ProjectDeviceAuthorizationAuthorization (

    @SerialName(value = "_type") @Required val type: ProjectDeviceAuthorizationAuthorization.Type,

    @SerialName(value = "creator") @Required val creator: ProjectDeviceAuthorizationAuthorizationCreator,

    @SerialName(value = "creator_id") @Required val creatorId: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "inserted_at") @Required val insertedAt: kotlinx.datetime.Instant,

    @SerialName(value = "project_device_id") @Required val projectDeviceId: kotlin.String,

    @SerialName(value = "scopes") @Required val scopes: ProjectDeviceAuthorizationAuthorizationScopes,

    @SerialName(value = "expires_at") val expiresAt: kotlinx.datetime.Instant? = null

) {

    /**
     * 
     *
     * Values: project_device_authorization
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "project_device_authorization") project_device_authorization("project_device_authorization");
    }

}

