/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param type 
 * @param id 
 * @param name 
 */
@Serializable

data class ProjectDeviceAuthorizationAuthorizationCreator (

    @SerialName(value = "_type") @Required val type: ProjectDeviceAuthorizationAuthorizationCreator.Type,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String

) {

    /**
     * 
     *
     * Values: user
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "user") user("user");
    }

}

