/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param cover 
 * @param finalized 
 * @param h2641080Best 
 * @param h2642160 
 * @param h264360 
 * @param h264540 
 * @param h264720 
 * @param imageFull 
 * @param imageHigh 
 * @param pageProxy 
 * @param thumb 
 * @param thumb540 
 * @param thumbOrigAr540 
 * @param thumbScrub 
 */
@Serializable

data class RequiredTranscodes (

    @SerialName(value = "cover") val cover: kotlin.Boolean? = null,

    @SerialName(value = "finalized") val finalized: kotlin.collections.List<RequiredTranscodes.Finalized>? = null,

    @SerialName(value = "h264_1080_best") val h2641080Best: kotlin.Boolean? = null,

    @SerialName(value = "h264_2160") val h2642160: kotlin.Boolean? = null,

    @SerialName(value = "h264_360") val h264360: kotlin.Boolean? = null,

    @SerialName(value = "h264_540") val h264540: kotlin.Boolean? = null,

    @SerialName(value = "h264_720") val h264720: kotlin.Boolean? = null,

    @SerialName(value = "image_full") val imageFull: kotlin.Boolean? = null,

    @SerialName(value = "image_high") val imageHigh: kotlin.Boolean? = null,

    @SerialName(value = "page_proxy") val pageProxy: kotlin.Boolean? = null,

    @SerialName(value = "thumb") val thumb: kotlin.Boolean? = null,

    @SerialName(value = "thumb_540") val thumb540: kotlin.Boolean? = null,

    @SerialName(value = "thumb_orig_ar_540") val thumbOrigAr540: kotlin.Boolean? = null,

    @SerialName(value = "thumb_scrub") val thumbScrub: kotlin.Boolean? = null

) {

    /**
     * 
     *
     * Values: thumb,thumb_540,thumb_scrub,image_full,image_high,cover,h264_360,h264_540,h264_720,h264_1080_best,h264_2160,page_proxy,thumb_orig_ar_540
     */
    @Serializable
    enum class Finalized(val value: kotlin.String) {
        @SerialName(value = "thumb") thumb("thumb"),
        @SerialName(value = "thumb_540") thumb_540("thumb_540"),
        @SerialName(value = "thumb_scrub") thumb_scrub("thumb_scrub"),
        @SerialName(value = "image_full") image_full("image_full"),
        @SerialName(value = "image_high") image_high("image_high"),
        @SerialName(value = "cover") cover("cover"),
        @SerialName(value = "h264_360") h264_360("h264_360"),
        @SerialName(value = "h264_540") h264_540("h264_540"),
        @SerialName(value = "h264_720") h264_720("h264_720"),
        @SerialName(value = "h264_1080_best") h264_1080_best("h264_1080_best"),
        @SerialName(value = "h264_2160") h264_2160("h264_2160"),
        @SerialName(value = "page_proxy") page_proxy("page_proxy"),
        @SerialName(value = "thumb_orig_ar_540") thumb_orig_ar_540("thumb_orig_ar_540");
    }

}

