/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import dev.androidbroadcast.framesdk.models.Asset
import dev.androidbroadcast.framesdk.models.ReviewLink

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param asset 
 * @param assetId 
 * @param deletedAt 
 * @param index 
 * @param insertedAt 
 * @param reviewLink 
 * @param reviewLinkId 
 * @param updatedAt 
 */
@Serializable

data class ReviewLinkItem (

    @SerialName(value = "asset") val asset: Asset? = null,

    @SerialName(value = "asset_id") val assetId: kotlin.String? = null,

    @SerialName(value = "deleted_at") val deletedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "index") val index: kotlin.Int? = null,

    @SerialName(value = "inserted_at") val insertedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "review_link") val reviewLink: ReviewLink? = null,

    @SerialName(value = "review_link_id") val reviewLinkId: kotlin.String? = null,

    @SerialName(value = "updated_at") val updatedAt: kotlinx.datetime.Instant? = null

) {


}

