/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import dev.androidbroadcast.framesdk.models.SessionWatermarkDataPoint

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param alpha 
 * @param dataPoints 
 * @param fontSize 
 * @param name 
 * @param position 
 * @param positionReferencePoint 
 * @param positionX 
 * @param positionY 
 * @param scrollText 
 * @param textAlignment 
 * @param textColor 
 * @param textShadow 
 */
@Serializable

data class SessionWatermarkBlock (

    @SerialName(value = "alpha") val alpha: kotlin.Double? = (0.5).toDouble(),

    @SerialName(value = "data_points") val dataPoints: kotlin.collections.List<SessionWatermarkDataPoint>? = null,

    @SerialName(value = "font_size") val fontSize: SessionWatermarkBlock.FontSize? = FontSize.medium,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "position") val position: SessionWatermarkBlock.Position? = Position.top_left,

    @SerialName(value = "position_reference_point") val positionReferencePoint: SessionWatermarkBlock.PositionReferencePoint? = null,

    @SerialName(value = "position_x") val positionX: kotlin.Int? = null,

    @SerialName(value = "position_y") val positionY: kotlin.Int? = null,

    @SerialName(value = "scroll_text") val scrollText: SessionWatermarkBlock.ScrollText? = ScrollText.none,

    @SerialName(value = "text_alignment") val textAlignment: SessionWatermarkBlock.TextAlignment? = TextAlignment.left,

    @SerialName(value = "text_color") val textColor: kotlin.String? = "#FFFFFF",

    @SerialName(value = "text_shadow") val textShadow: kotlin.Boolean? = false

) {

    /**
     * 
     *
     * Values: small,medium,large,huge
     */
    @Serializable
    enum class FontSize(val value: kotlin.String) {
        @SerialName(value = "small") small("small"),
        @SerialName(value = "medium") medium("medium"),
        @SerialName(value = "large") large("large"),
        @SerialName(value = "huge") huge("huge");
    }
    /**
     * 
     *
     * Values: top_left,top_center,top_right,middle_left,middle_center,middle_right,bottom_left,bottom_center,bottom_right
     */
    @Serializable
    enum class Position(val value: kotlin.String) {
        @SerialName(value = "top_left") top_left("top_left"),
        @SerialName(value = "top_center") top_center("top_center"),
        @SerialName(value = "top_right") top_right("top_right"),
        @SerialName(value = "middle_left") middle_left("middle_left"),
        @SerialName(value = "middle_center") middle_center("middle_center"),
        @SerialName(value = "middle_right") middle_right("middle_right"),
        @SerialName(value = "bottom_left") bottom_left("bottom_left"),
        @SerialName(value = "bottom_center") bottom_center("bottom_center"),
        @SerialName(value = "bottom_right") bottom_right("bottom_right");
    }
    /**
     * 
     *
     * Values: top_left,top_center,top_right,middle_left,middle_center,middle_right,bottom_left,bottom_center,bottom_right
     */
    @Serializable
    enum class PositionReferencePoint(val value: kotlin.String) {
        @SerialName(value = "top_left") top_left("top_left"),
        @SerialName(value = "top_center") top_center("top_center"),
        @SerialName(value = "top_right") top_right("top_right"),
        @SerialName(value = "middle_left") middle_left("middle_left"),
        @SerialName(value = "middle_center") middle_center("middle_center"),
        @SerialName(value = "middle_right") middle_right("middle_right"),
        @SerialName(value = "bottom_left") bottom_left("bottom_left"),
        @SerialName(value = "bottom_center") bottom_center("bottom_center"),
        @SerialName(value = "bottom_right") bottom_right("bottom_right");
    }
    /**
     * 
     *
     * Values: none,ltr,rtl
     */
    @Serializable
    enum class ScrollText(val value: kotlin.String) {
        @SerialName(value = "none") none("none"),
        @SerialName(value = "ltr") ltr("ltr"),
        @SerialName(value = "rtl") rtl("rtl");
    }
    /**
     * 
     *
     * Values: left,right,center
     */
    @Serializable
    enum class TextAlignment(val value: kotlin.String) {
        @SerialName(value = "left") left("left"),
        @SerialName(value = "right") right("right"),
        @SerialName(value = "center") center("center");
    }

}

