/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import dev.androidbroadcast.framesdk.models.ShareableEntityAccessControl

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param accessControl 
 * @param assetId 
 * @param autoplay 
 * @param backgroundColor 
 * @param canDownload 
 * @param color 
 * @param deletedAt 
 * @param description 
 * @param enabled 
 * @param expiresAt 
 * @param format 
 * @param includeExt 
 * @param includeUploadDate 
 * @param layout 
 * @param name 
 * @param ownerId 
 * @param password 
 * @param projectId 
 * @param secure 
 * @param style 
 * @param textColor 
 * @param title 
 */
@Serializable

data class UpdatePresentationRequest (

    @SerialName(value = "access_control") val accessControl: ShareableEntityAccessControl? = null,

    @SerialName(value = "asset_id") val assetId: kotlin.String? = null,

    @SerialName(value = "autoplay") val autoplay: kotlin.Boolean? = null,

    @SerialName(value = "background_color") val backgroundColor: kotlin.String? = null,

    @SerialName(value = "can_download") val canDownload: kotlin.Boolean? = null,

    @SerialName(value = "color") val color: kotlin.String? = null,

    @SerialName(value = "deleted_at") val deletedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "enabled") val enabled: kotlin.Boolean? = null,

    @SerialName(value = "expires_at") val expiresAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "format") val format: kotlin.String? = null,

    @SerialName(value = "include_ext") val includeExt: kotlin.Boolean? = null,

    @SerialName(value = "include_upload_date") val includeUploadDate: kotlin.Boolean? = null,

    @SerialName(value = "layout") val layout: UpdatePresentationRequest.Layout? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "owner_id") val ownerId: kotlin.String? = null,

    @SerialName(value = "password") val password: kotlin.String? = null,

    @SerialName(value = "project_id") val projectId: kotlin.String? = null,

    @SerialName(value = "secure") val secure: kotlin.Boolean? = null,

    @SerialName(value = "style") val style: kotlin.String? = null,

    @SerialName(value = "text_color") val textColor: kotlin.String? = null,

    @SerialName(value = "title") val title: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: blog,reel
     */
    @Serializable
    enum class Layout(val value: kotlin.String) {
        @SerialName(value = "blog") blog("blog"),
        @SerialName(value = "reel") reel("reel");
    }

}

