/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param admin 
 * @param id 
 * @param sales 
 * @param support 
 */
@Serializable

data class UserRoles (

    @SerialName(value = "admin") val admin: kotlin.Boolean? = null,

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "sales") val sales: kotlin.Boolean? = null,

    @SerialName(value = "support") val support: kotlin.Boolean? = null

) {


}

