/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import dev.androidbroadcast.framesdk.models.UserRoles

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * User model
 *
 * @param digestFrequency 
 * @param featuresSeen 
 * @param profileImageOriginal 
 * @param image32 
 * @param image128 
 * @param fromGoogle 
 * @param mfaEnforcedAt 
 * @param email 
 * @param bio 
 * @param name 
 * @param image64 
 * @param timezoneValue 
 * @param accountId 
 * @param updatedAt 
 * @param image256 
 * @param type 
 * @param userHash 
 * @param context 
 * @param uploadUrl 
 * @param location 
 * @param phone 
 * @param deletedAt 
 * @param profileImage 
 * @param firstLoginAt 
 * @param joinedVia 
 * @param emailConfirmBy 
 * @param id 
 * @param nextDigestDate 
 * @param emailPreferences 
 * @param lastSeen 
 * @param insertedAt 
 * @param roles 
 * @param userDefaultColor 
 */
@Serializable

data class User (

    @SerialName(value = "digest_frequency") val digestFrequency: kotlin.String? = null,

    @SerialName(value = "features_seen") val featuresSeen: kotlin.Any? = null,

    @SerialName(value = "profile_image_original") val profileImageOriginal: kotlin.Any? = null,

    @SerialName(value = "image_32") val image32: kotlin.String? = null,

    @SerialName(value = "image_128") val image128: kotlin.String? = null,

    @SerialName(value = "from_google") val fromGoogle: kotlin.Boolean? = null,

    @SerialName(value = "mfa_enforced_at") val mfaEnforcedAt: kotlin.String? = null,

    @SerialName(value = "email") val email: kotlin.String? = null,

    @SerialName(value = "bio") val bio: kotlin.Any? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "image_64") val image64: kotlin.String? = null,

    @SerialName(value = "timezone_value") val timezoneValue: kotlin.String? = null,

    @SerialName(value = "account_id") val accountId: kotlin.String? = null,

    @SerialName(value = "updated_at") val updatedAt: kotlin.String? = null,

    @SerialName(value = "image_256") val image256: kotlin.String? = null,

    @SerialName(value = "_type") val type: kotlin.String? = null,

    @SerialName(value = "user_hash") val userHash: kotlin.String? = null,

    @SerialName(value = "context") val context: kotlin.Any? = null,

    @SerialName(value = "upload_url") val uploadUrl: kotlin.String? = null,

    @SerialName(value = "location") val location: kotlin.Any? = null,

    @SerialName(value = "phone") val phone: kotlin.Any? = null,

    @SerialName(value = "deleted_at") val deletedAt: kotlin.Any? = null,

    @SerialName(value = "profile_image") val profileImage: kotlin.String? = null,

    @SerialName(value = "first_login_at") val firstLoginAt: kotlin.String? = null,

    @SerialName(value = "joined_via") val joinedVia: kotlin.String? = null,

    @SerialName(value = "email_confirm_by") val emailConfirmBy: kotlin.Any? = null,

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "next_digest_date") val nextDigestDate: kotlin.String? = null,

    @SerialName(value = "email_preferences") val emailPreferences: kotlin.Any? = null,

    @SerialName(value = "last_seen") val lastSeen: kotlin.String? = null,

    @SerialName(value = "inserted_at") val insertedAt: kotlin.String? = null,

    @SerialName(value = "roles") val roles: UserRoles? = null,

    @SerialName(value = "user_default_color") val userDefaultColor: kotlin.String? = null

) {


}

