/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import dev.androidbroadcast.framesdk.models.Image

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param alpha 
 * @param image 
 * @param position 
 */
@Serializable

data class WatermarkImage (

    @SerialName(value = "alpha") val alpha: kotlin.Double? = (0.5).toDouble(),

    @SerialName(value = "image") val image: Image? = null,

    @SerialName(value = "position") val position: WatermarkImage.Position? = Position.top_left

) {

    /**
     * 
     *
     * Values: top_left,top_right,bottom_left,bottom_right
     */
    @Serializable
    enum class Position(val value: kotlin.String) {
        @SerialName(value = "top_left") top_left("top_left"),
        @SerialName(value = "top_right") top_right("top_right"),
        @SerialName(value = "bottom_left") bottom_left("bottom_left"),
        @SerialName(value = "bottom_right") bottom_right("bottom_right");
    }

}

