/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.androidbroadcast.framesdk.models

import dev.androidbroadcast.framesdk.models.Events
import dev.androidbroadcast.framesdk.models.Team

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param accountId 
 * @param active 
 * @param appId 
 * @param deletedAt 
 * @param events 
 * @param id 
 * @param insertedAt 
 * @param name 
 * @param projectId 
 * @param secret 
 * @param team 
 * @param teamId 
 * @param updatedAt 
 * @param url 
 */
@Serializable

data class Webhook (

    @SerialName(value = "account_id") val accountId: kotlin.String? = null,

    @SerialName(value = "active") val active: kotlin.Boolean? = null,

    @SerialName(value = "app_id") val appId: kotlin.String? = null,

    @SerialName(value = "deleted_at") val deletedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "events") val events: kotlin.collections.List<Events>? = null,

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "inserted_at") val insertedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "project_id") val projectId: kotlin.String? = null,

    @SerialName(value = "secret") val secret: kotlin.String? = null,

    @SerialName(value = "team") val team: Team? = null,

    @SerialName(value = "team_id") val teamId: kotlin.String? = null,

    @SerialName(value = "updated_at") val updatedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "url") val url: kotlin.String? = null

) {


}

